<?php
/**
 * Created by PhpStorm.
 * User: ihuanglele<huanglele@yousuowei.cn>
 * Date: 2019-11-11
 * Time: 13:49
 */

namespace fw\cache;


use fw\Cache;

class Redis extends Cache
{

    protected $conf = [];

    protected function getConn()
    {

    }

    public function __construct($conf)
    {

    }

    public function set($key, $value, $expire)
    {
        return parent::set($key, $value, $expire); // TODO: Change the autogenerated stub
    }

}