<?php
/**
 * Created by PhpStorm.
 * User: ihuanglele<huanglele@yousuowei.cn>
 * Date: 2019-01-21
 * Time: 16:06
 */

namespace fw;

use function json_encode;
use const JSON_UNESCAPED_UNICODE;
use function method_exists;

class Controller extends \Yaf\Controller_Abstract
{

    /**
     * @return Request
     * @author ihuanglele<ihuanglele@yousuowei.cn>
     * @time 2019-02-11
     */
    public function getRequest()
    {
        return parent::getRequest(); // TODO: Change the autogenerated stub
    }

    public function init()
    {
        // add Header
        if(method_exists($this->getResponse(),'setHeader')){
            $this->getResponse()->setHeader('Content-Type', 'application/json;charset=utf-8');
            $this->getResponse()->setHeader('Server', 'Apache/1.8.0');
            $this->getResponse()->setHeader('X-Powered-By', 'YafRest');
            $this->getResponse()->setHeader('Access-Control-Allow-Origin', '*');
            $this->getResponse()->setHeader('Access-Control-Allow-Methods', 'GET,OPTIONS,POST,HEAD,DELETE');
            $this->getResponse()->setHeader('Access-Control-Allow-Headers', 'Content-Type,Token,X-Agent,Accept');
            $this->getResponse()->setHeader('Access-Control-Allow-Credentials', 'true');
        }
    }

    /**
     * 获取 get 参数
     * @param string|null $name
     * @param mixed $default
     * @return mixed
     * @author ihuanglele<huanglele@yousuowei.cn>
     * @time 2019-01-21
     */
    protected function get($name = null, $default = null)
    {
        if(CLI){
            return null;
        }
        return $this->getRequest()->get($name, $default);
    }

    /**
     * 获取 post 参数
     * @param string|null $name
     * @param mixed $default
     * @return mixed
     * @author ihuanglele<ihuanglele@yousuowei.cn>
     * @time 2019-02-12
     */
    protected function post($name = null, $default = null)
    {
        if(CLI){
            return null;
        }
        return $this->getRequest()->post($name, $default);
    }

    /**
     * 成功返回
     * @param string|array $data
     * @author ihuanglele<ihuanglele@yousuowei.cn>
     * @time 2019-01-21
     */
    protected function success($data)
    {
        $this->getResponse()->setBody(json_encode(['code' => 200, 'data' => $data], JSON_UNESCAPED_UNICODE));
        //        throw new ResponseException();
    }

    /**
     * 失败返回
     * @param string $msg
     * @param int $code
     * @author ihuanglele<ihuanglele@yousuowei.cn>
     * @time 2019-01-21
     */
    protected function error($msg, $code = 0)
    {
        $this->getResponse()->setBody(json_encode(['code' => $code, 'msg' => $msg], JSON_UNESCAPED_UNICODE));
        //        throw new ResponseException();
    }

}