<?php
/**
 * Created by PhpStorm.
 * Author ihuanglele<huanglele@yousuowei.cn>
 * Date: 2019-02-01
 * Time: 16:47
 */

namespace fw;

/**
 * 封装一层 Request 用于统一参数、参数过滤
 */

use function explode;

class Request extends \Yaf\Request\Http
{


    public function __construct(string $request_uri = '', string $base_uri = '')
    {
        if (empty($request_uri)) {
            list($request_uri) = explode('?', $_SERVER['REQUEST_URI']);
        }
        parent::__construct($request_uri, $base_uri);
    }

    public function get($name, $default = null)
    {
        parent::get($name, $default); // TODO: Change the autogenerated stub
    }

}